scrape_configs:
  - job_name: 'postgres-metabase'
    static_configs:
      - targets:
        - 'postgres-exporter:9187'

  - job_name: 'statsd-exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'statsd-exporter:9102'